openapi: 3.0.0
info:
  title: Scrum API
  description: "Scrum API doc"
  version: 0.1.0

tags:
  - name: Boards
    description: "CRUD board operations"


paths:
  /boards/{board_id}:
    get:
      tags:
        - Boards
      summary: Get board
      parameters:
        - $ref: "#/components/parameters/ParamsBoardId"
      responses:
        "200":
          $ref: "#/components/responses/GetBoardResult"


components:
  parameters:
    ParamsBoardId:
      name: board_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/BoardId"


  schemas:
    BoardId:
      type: string
      format: uuid
      description: ""
      example: "c70c3dd8-ead1-43b7-8ee6-1c9fc4c3233f"

    BoardTitle:
      type: string
      description: ""
      example: "Europe/Moscow"

    BoardCreatorId:
      type: string
      format: uuid
      description: ""
      example: "c90c3dd8-ead1-43b7-8ee6-1c9fc4c3233f"

    BoardCreatedAt:
      type: integer
      description: ""
      nullable: false
      example: 1577836800

    Board:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/BoardTitle"
        creator_id:
          $ref: "#/components/schemas/BoardCreatorId"
        created_at:
          $ref: "#/components/schemas/BoardCreatedAt"


  responses:
    GetBoardResult:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                $ref: "#/components/schemas/Board"

x-tagGroups:
  - name: Main
    tags:
      - Boards