openapi: 3.0.0
info:
  title: Scrum API
  description: "Scrum API doc"
  version: 0.1.0

tags:
  - name: Authorization
    description: "oauth operations"
  - name: Boards
    description: "CRUD board operations"
  - name: Cards
    description: "CRUD card operations"

paths:
  /oauth:
    post:
      tags:
        - Authorization
      summary: Login
      requestBody:
        $ref: "#/components/requestBodies/AuthorizationParams"
      responses:
        "200":
          $ref: "#/components/responses/AuthorizationResult"
#        400:
#          $ref: "../swagger/responses.yaml#/InputDataErrorResponse"
#        500:
#          $ref: "../swagger/responses.yaml#/DatabaseErrorResponse"

  /boards/{board_id}:
    get:
      tags:
        - Boards
      summary: Get board
      parameters:
        - $ref: "#/components/parameters/ParamsBoardId"
      responses:
        "200":
          $ref: "#/components/responses/GetBoardResult"
    patch:
      tags:
        - Boards
      summary: Update board
      parameters:
        - $ref: "#/components/parameters/ParamsBoardId"
      requestBody:
        $ref: "#/components/requestBodies/UpdateBoardBody"
      responses:
        "204":
          $ref: "#/components/responses/EmptyOkResponse"
    delete:
      tags:
        - Boards
      summary: Delete board
      parameters:
        - $ref: "#/components/parameters/ParamsBoardId"
      responses:
        "200":
          $ref: "#/components/responses/EmptyOkResponse"

  /boards:
    get:
      tags:
        - Boards
      summary: Get board list
      responses:
        "200":
          $ref: "#/components/responses/GetBoardListResult"
    post:
      tags:
        - Boards
      summary: Create board
      requestBody:
        $ref: "#/components/requestBodies/CreateBoardBody"
      responses:
        "200":
          $ref: "#/components/responses/CreatedBoardResult"

  /cards/report:
    get:
      tags:
        - Cards
      summary: Get card list / (report)
      parameters:
        - $ref: "#/components/parameters/ParamsBoardId"
        - $ref: "#/components/parameters/ParamsPriority"
        - $ref: "#/components/parameters/ParamsStatus"
        - $ref: "#/components/parameters/ParamsDeveloperId"
      responses:
        "200":
          $ref: "#/components/responses/ReportCardResult"

components:
  parameters:
    # ------BOARD------
    ParamsBoardId:
      name: board_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/BoardId"

    # ------CARD------
    ParamsPriority:
      name: priority
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Priority"

    ParamsStatus:
      name: status
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/Status"

    ParamsDeveloperId:
      name: developer_id
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/DeveloperId"

  requestBodies:
    # ------OAUTH------
    AuthorizationParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthorizationBody'
      required: true
    # ------BOARD------
    CreateBoardBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateBoardBody"
      required: true

    UpdateBoardBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateBoardBody"
      required: true

  schemas:
    # ------CARDS------
    Priority:
      type: string
      description: "Сard priority"
      enum:
        - Low
        - Normal
        - High
        - Immediate
      example: low

    Status:
      type: string
      description: "Сard status"
      enum:
        - New
        - In development
        - Developed
        - On hold
        - Closed
      example: New

    DeveloperId:
      type: string
      format: uuid
      description: ""
      example: "c90c3dd8-ead1-43b7-8ee6-1c9fc4c3233f"

    Estimation:
      type: string
      description: "ideal working hours"
      example: "8h"

    # ------OAUTH------
    Login:
      type: string
      description: "User login"
      nullable: false
      example: "admin"

    Password:
      type: string
      description: "User password"
      nullable: false
      example: "admin"

    Token:
      type: string
      description: "jwt token"
      nullable: false
      example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleGFtcGxlIjoiand0X3Rva2VuIn0.MXPuwZMnFH7HBdLICjtT9tmAgVnSAPi3m45i6j6y7aA"

    AuthorizationBody:
      type: object
      properties:
        login:
          $ref: '#/components/schemas/Login'
        password:
          $ref: '#/components/schemas/Password'
      required:
        - username
        - password

    # ------BOARD------
    BoardId:
      type: string
      format: uuid
      description: ""
      example: "c70c3dd8-ead1-43b7-8ee6-1c9fc4c3233f"

    BoardTitle:
      type: string
      description: ""
      example: "Board display name"

    BoardCreatorId:
      type: string
      format: uuid
      description: ""
      example: "c90c3dd8-ead1-43b7-8ee6-1c9fc4c3233f"

    BoardCreatedAt:
      type: integer
      description: ""
      nullable: false
      example: 1577836800

    Board:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/BoardTitle"
        creator_id:
          $ref: "#/components/schemas/BoardCreatorId"
        created_at:
          $ref: "#/components/schemas/BoardCreatedAt"

    CreateBoardBody:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/BoardTitle"

    UpdateBoardBody:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/BoardTitle"

    count:
      type: integer
      minimum: 0
      description: "Количество сущностей"
      example: 1

    BoardsAll:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/BoardId"
        title:
          $ref: "#/components/schemas/BoardTitle"
        creator_id:
          $ref: "#/components/schemas/BoardCreatorId"
        created_at:
          $ref: "#/components/schemas/BoardCreatedAt"

    # ------CARDS------
    Description:
      type: integer
      minimum: 0
      description: ""
      example: "description card"

    CreatedAt:
      type: integer
      description: ""
      nullable: false
      example: 1577836800
    UpdatedAt:
      type: integer
      description: ""
      nullable: false
      example: 1577836800

    CardsAll:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/BoardId"
        description:
          $ref: "#/components/schemas/Description"
        developer_id:
          $ref: "#/components/schemas/CreatorId"
        priority:
          $ref: "#/components/schemas/Priority"
        status:
          $ref: "#/components/schemas/Status"
        estimates_time:
          $ref: "#/components/schemas/Estimates"
        board_id:
          $ref: "#/components/schemas/BoardId"
        creator_id:
          $ref: "#/components/schemas/CreatorId"
        created_at:
          $ref: "#/components/schemas/CreatedAt"
        updated_at:
          $ref: "#/components/schemas/UpdatedAt"

  responses:
    # ------OAUTH------
    AuthorizationResult:
      description: "Authorization Token"
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                $ref: '#/components/schemas/Token'
    # ------BOARD------
    GetBoardResult:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                $ref: "#/components/schemas/Board"

    GetBoardListResult:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                $ref: '#/components/schemas/count'
              boards:
                type: array
                items:
                  $ref: '#/components/schemas/BoardsAll'

    CreatedBoardResult:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                $ref: "#/components/schemas/BoardId"
              created_at:
                $ref: "#/components/schemas/BoardCreatedAt"

    # ------CARDS------
    ReportCardResult:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              count:
                $ref: '#/components/schemas/count'
              estimation:
                $ref: '#/components/schemas/Estimation' # 8h
              cards:
                type: array
                items:
                  $ref: '#/components/schemas/CardsAll'

    # ------ERRORS------
    EmptyOkResponse:
      description: Accepted
      content: {}

x-tagGroups:
  - name: Main
    tags:
      - Authorization
      - Boards
      - Cards