version: "3.3"

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: always
#    ports:
#      - "5442:5432"

  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    command: python __main__.py
    depends_on:
      - database
    ports:
      - "8888:8888"
    networks:
      - default
