ERROR_CARD_ID_NOT_FOUND = "Card id not found"
ERROR_DEVELOPER_NOT_FOUND = "Developer not found"
ERROR_PRIORITY_NOT_FOUND = "Priority not found"
ERROR_STATUS_NOT_FOUND = "Status not found"
ERROR_BOARD_NOT_FOUND = "Bord not found"
